[general]
# How often are the targets being checked (hours)
check_interval = 12
# How many days before cert expiration are alerts being sent
alert_period = [ 14, 7, 1 ]

[[target]]
hostname = "example.com"
port = 443
expect_status = 200

